# URL where Public Whip XML data files can be found
xml_data_base_url: http://data.openaustralia.org/

# Name of project to display thoughout the application
project_name: They Vote For You
contact_email: contact@theyvoteforyou.org.au
time_zone: Sydney

# Hack so that application can know what stage we're in (used for creating sensible partitioned index names
# for elasticsearch). This would be more sensibly be done with the environment
stage: test
